repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: debug-statements
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    - id: reorder-python-imports
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
            -   flake8-bugbear
            -   flake8-comprehensions
            -   flake8-docstrings
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
    -   id: pylint
        files: .
        exclude: (?x)^(docs/source/conf.py)$
        args:
            - --disable=import-error,no-member
            - --max-locals=20
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    -   id: mypy
        args: [--install-types, --non-interactive]
        additional_dependencies:
          - types-toml
          - types-PyYAML
          - types-jinja2
          - types-click
          - typer
          - rich
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    -   id: codespell
-   repo: https://github.com/myint/docformatter
    rev: v1.6.5
    hooks:
    -   id: docformatter
